############################################################################################
# Configuration for the PM Connect Conf 2025 website built with Hugo and a custom theme.   #
# Developed and maintained by Maciej Koszykowski.                                          #
# Enable or disable sections using the 'enable' parameter as needed in YAML files          #
# Original theme settings remain here for reference and may be removed in future updates.  #
############################################################################################

title = "PM Connect Conf"
theme = "navigator-hugo" # TODO: once the theme evolve change the name to more proper 
languageCode = "pl"

## TODO: currenlty hardcoded 
# google analytics tracking id
# googleAnalytics = "DIFFRENT" # NOT USED HARDCODED IN THEME ###

baseURL = "https://pmcc.pmi.org.pl"  # Main site URL; for old edition archive use "https://pmcc.pmi.org.pl/YYYY" 
homeURL = "https://pmcc.pmi.org.pl"  # Allows easy navigation back to the current edition from previous ones

# Note from Maciej Koszykowski: 
    # Previous editions are maintained as static pages (e.g., /2024) for easier management,
    # especially if the theme or development tools change. We don't need to worry later about these aspects. 
    # On GitHub, editions will be branched separately, but static retention ensures smooth transitions
    # regardless of who manages development or future environment changes.



###########################################################
## Page params which normally does not need to be changed #
###########################################################

enableRobotsTXT = true       # This generates robots.txt by Hugo. This file tells search engines how to crawl and index your site.
enableGitInfo = false        # in Hugo enables inclusion of Git commit metadata (like last modified date) for your content files during site generation.
pygmentsCodeFences = true    # Might be useful so on. This enables syntax highlighting for code blocks fenced with triple backticks (```) using the Pygments highlighter in Hugo.

#In Hugo, the [markup] section configures how Markdown is processed.
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true # allows HTML tags and raw HTML inside Markdown files to be rendered as-is rather than escaped or stripped out.


###########################################################
## Other Site Params which are not Hugo built-in          #
###########################################################

[params]
logo = "images/pmcc_logo.svg" # conf logo, normally we replace the file not setting here

# TODO: are all really used? 
logo_xsmall = "images/pmcc_logo_bar_xsmall.png"
logo_large = "images/pmcc_logo_large.png"
logo_pmi = "images/logo_pmi_kuj_pom_50.png"
logo_umk = "images/logo_WNEiZ_UMK_50.png"

# paga meta data
author = "PMI and UMK"
description =  "PM Connect Conf to dynamiczna inicjatywa współorganizowana przez kujawsko-pomorski oddział PMI Poland Chapter oraz Wydział Nauk Ekonomicznych i Zarządzania UMK w Toruniu. PM Connect Conf to nie tylko wyjątkowa szansa na poszerzenie praktycznej wiedzy z zakresu project managementu, ale także okazja do inspirującego networkingu w gronie profesjonalistów. Dzięki spotkaniu z ekspertami i liderami branży, uczestnicy będą mogli wymienić się doświadczeniami i nawiązać wartościowe kontakty, które mogą przyczynić się do dalszego rozwoju ich kariery zawodowej."


#TODO is it really used ??
dateFormat = "January 2, 2006" #TODO: this is not Polish date format
confStartDate = "2025-10-25T10:00:00" #extact date with hrs - this is counting down 


# menu - first option # navbar 
home = "Start"
menufixed = true

footerServiceTitle = "images/poland_logo-small.png"
footerQuicklinkTitle = "Mapa Strony"
footerAboutTitle = "Organizator"
PMI_PC="PMI Poland Chapter"
PMI_PC_pl="(PMI Oddział Polski)"
PMI_PC_address_ul="ul. Domaniewska 47/10"
PMI_PC_address_code="02-672 Warszawa"
PMI_PC_NIP= "NIP: 525-227-89-73"

# TODO: not used, probably to remove later 
footerSubscribeTitle = "Subscribe"


# cookies
[params.cookies]
enable = true
expire_days = 2

# TODO: hero to yaml 
# Hero Area Section - Top strony 
[params.hero]
enable = true #doubled with yaml #TODO one only please

heading = "PM CONNECT CONF 2025"
#description = "Sztuczna inteligencja w zarządzaniu projektami to już rzeczywistość"
description = "Nowa równowaga: <br> AI automatyzuje, PM humanizuje"

button = true
btnText = "Kup Bilet"
#btnText = "Zgłoś swój temat"

btnURL = "https://pmipolandchapter.ticketbutler.io/en/e/pm-connect-conf-pmcc-2025/"
#btnURL = "mailto:kujawsko-pomorskie@pmi.org.pl?subject=PMCC 2025 zgłoszenie prelekcji: temat wystąpienia&body=Imię i nazwisko: \nTytuł wystąpienia: \nKategoria: \n\nPrzesyłam rozszerzony abstrakt (do 4000 znaków): \n"


#########################
# YAML configuration    #
#########################

# Each page section should be configurable via an 'enable' parameter in the YAML config file.
# Each section should have a corresponding YAML configuration.
# If an original theme section has not yet been used or modified, this TOML file includes the original configuration just in case; these may be removed later.

# contact section is left here

# Blog Section On Homepage ####TODO: remove or reuse 
[params.blog]
enable = false #TODO: maybe the next year to use ? 
topTitle = "OUR UNTOLD STORY"
title = "Blog."
subtitle = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!"

# Contact Section
[params.contact]
enable = true
topTitle = "PM Connect Conf"
title = "Miejsce konferencji"
subtitle = " "
address = "Wydział Nauk Ekonomicznych i Zarządzania"
address_line2 = "UMK w Toruniu"
address_line3 = "ul. Gagarina 13a, 87-100 Toruń"
phone = "+48 790 778 940"

facebook = "https://www.facebook.com/events/997899829013535/?ref=newsfeed"
#twitter = "https://twitter.com/"
linkedin = "https://www.linkedin.com/events/pmconnectconf2024-zarz-dzaniepr7236639081965731840"
#dribbble = "https://dribbble.com/"
#instagram = "https://www.instagram.com/"

# TODO: not used, probably to remove later 
mapLatitude =  "53.02148"
mapLongitude = "18.57073"
mapMarker = "images/marker.png"
### end of TODO

# Call to Action Section on About Page
# TODO: not used, probably to remove later 
[params.cta]
enable = true
bg = "images/call-to-action/call-to-action-bg-2.jpg"
title = "Let's Create Something Together"
subtitle = "Proin gravida nibh vel velit auctor aliquet. Aenean sollicudin bibendum auctor, <br> nisi elit consequat ipsum, nesagittis sem nid elit. Duis sed odio sitain elit."
btnText = "Contact Us"
## end of TODO

# Site Menus

[menu]
# Navbar Menus
[[menu.nav]]
name = "Galeria"
url = "/galeria"
weight = 1

#[[menu.nav]] #call4papers
#name = "Call for papers"
#url = "#Prelegenci"
#weight = 2

[[menu.nav]]
name = "Prelegenci"
url = "#Prelegenci"
weight = 2

#[[menu.nav]]
#name = "Prowadzący"
#url = "#Prowadzacy"
#weight = 2


[[menu.nav]]
name = "Agenda"
url = "#Agenda"
weight = 4

#[[menu.nav]]
#name = "Panel"
#url = "#Panel"
#weight = 5

[[menu.nav]]
name = "Bilety"
url = "#Bilety"
weight = 7

[[menu.nav]]
name = "Partnerzy"
url = "#Partnerzy"
weight = 8

[[menu.nav]]
name = "Lokalizacja"
url = "#Lokalizacja"
weight = 10

[[menu.nav]]
name = "Zespół"
url = "#Zespol"
weight = 20

[[menu.nav]]
name = "Regulamin"
url = "regulamin"
weight = 26

[[menu.nav]]
name = "2024"
url = "https://pmcc.pmi.org.pl/2024"
weight = 27

# Footer Quick links Menu
[[menu.quicklink]]
name = "Polityka prywatności"
url = "Polityka-prywatnosci.pdf"
weight = 1
[[menu.quicklink]]
name = "Polityka ciasteczek"
url = "Polityka-ciasteczek.pdf"
weight = 2
[[menu.quicklink]]
name = "Regulamin"
url = "regulamin"
weight = 3

